development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://quqkritglbedpn:RiWBv7t-2ttcYY4KjOYYGtUE3e@ec2-174-129-209-53.compute-1.amazonaws.com:5432/d3fjl8vl214a8f
